version: '3.9'

services:
  # --- Kafka + Zookeeper + Ui ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    volumes:
      - kafka-data:/bitnami/kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: kafka
      SPRING_SECURITY_USER_PASSWORD: kafka
    volumes:
      - ./dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml

  # --- Spring Boot App ---
  xpayment-adapter:
    build:
      context: .
    container_name: xpayment-adapter
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5005:5005"
    volumes:
      - ./certs:/app/certs
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

volumes:
  kafka-data:
  kafka-ui-data:
